doc/configuration: mock DockerClient to stay compatible with recent docker package
docker==6.0.0 tries to connect already on `docker.DockerClient()`, so we
need to mock it for doctest to run successfully.

Fixes configuration.rst:2868 instantiating DockerStrategy with the
specified environment config:

    Traceback (most recent call last):
      File "/usr/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest docker-strategy[2]>", line 1, in <module>
        t = e.get_target("main")
      File "/path/to/labgrid/labgrid/environment.py", line 49, in get_target
        target = target_factory.make_target(role, config, env=self)
      File "/path/to/labgrid/labgrid/factory.py", line 151, in make_target
        self.make_resource(target, resource, name, args)
      File "/path/to/labgrid/labgrid/factory.py", line 123, in make_resource
        r = cls(target, name, **args)
      File "<attrs generated init labgrid.resource.docker.DockerDaemon>", line 13, in __init__
        self.__attrs_post_init__()
      File "/path/to/labgrid/labgrid/resource/docker.py", line 91, in __attrs_post_init__
        super().__attrs_post_init__()
      File "/path/to/labgrid/labgrid/resource/common.py", line 124, in __attrs_post_init__
        self.manager._add_resource(self)
      File "/path/to/labgrid/labgrid/resource/common.py", line 100, in _add_resource
        self.on_resource_added(resource)
      File "/path/to/labgrid/labgrid/resource/docker.py", line 52, in on_resource_added
        docker.DockerClient(base_url=resource.docker_daemon_url)
      File "/path/to/labgrid/venv/lib/python3.9/site-packages/docker/client.py", line 45, in __init__
        self.api = APIClient(*args, **kwargs)
      File "/path/to/labgrid/venv/lib/python3.9/site-packages/docker/api/client.py", line 197, in __init__
        self._version = self._retrieve_server_version()
      File "/path/to/labgrid/venv/lib/python3.9/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
        raise DockerException(
    docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

Signed-off-by: Bastian Krause <bst@pengutronix.de>