target: mention driver causing NoSupplierFoundErrors
NoSupplierFoundError and its sub classes are hard to understand if the
driver/strategy causing it is not mentioned:

  NoDriverFoundError: multiple drivers matching ConsoleProtocol found in Target(name='main', env=Environment(config_file='env.yaml')) with the same priorities

Improve this by rasing a more detailed exception from the original
exception with this information included:

  NoDriverFoundError: binding MyStrategy failed: multiple drivers matching ConsoleProtocol found in Target(name='main', env=Environment(config_file='env.yaml')) with the same priorities

Signed-off-by: Bastian Krause <bst@pengutronix.de>