pytestplugin/hooks: only set coordinator if env exists
This fixes

  AttributeError: 'NoneType' object has no attribute 'config'

in case --lg-coordinator is given but --lg-env (or LG_ENV) is missing.

Signed-off-by: Bastian Krause <bst@pengutronix.de>