github: install setuptools_scm via apt
Installing setuptools_scm via pip system-wide is deprecated. With
ubuntu 24.04 this becomes an error:

    pip install --upgrade setuptools
    pip install setuptools_scm

  WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

  Reading package lists...
  Building dependency tree...
  Reading state information...
  python3-pip is already the newest version (24.0+dfsg-1ubuntu1).
  0 upgraded, 0 newly installed, 0 to remove and 15 not upgraded.
  error: externally-managed-environment

  × This environment is externally managed
  ╰─> To install Python packages system-wide, try apt install
      python3-xyz, where xyz is the package you are trying to
      install.

      If you wish to install a non-Debian-packaged Python package,
      create a virtual environment using python3 -m venv path/to/venv.
      Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
      sure you have python3-full installed.

      If you wish to install a non-Debian packaged Python application,
      it may be easiest to use pipx install xyz, which will manage a
      virtual environment for you. Make sure you have pipx installed.

      See /usr/share/doc/python3.12/README.venv for more information.

  note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
  hint: See PEP 668 for the detailed specification.

labgrid does not rely on a special version of setuptools_scm anyway, so
simply install the corresponding Ubuntu package.

Signed-off-by: Bastian Krause <bst@pengutronix.de>