util/ssh: protect keepalive subprocess from CTRL-C
When using labgrid-client export with an ssh-based driver (such as
NetworkInterfaceDriver), stopping it with CTRL-C caused:
  labgrid.driver.exception.ExecutionError: SSHConnection.disconnect can not be
  called (SSHConnection(host='lxatac-00006', _connected=True,
  _tmpdir='/tmp/labgrid-connection-qdc5ldt0', _l_forwards={},
  _r_forwards=set()) is not connected)

This turned out to be an error caused by the keepalive ssh process being
terminated before labgrid had a chance to shut it down. Solve this by starting
the subprocess in a separate session, which isolates it from CTRL-C.

Signed-off-by: Jan Luebbe <jlu@pengutronix.de>