doc: fix inline interpreted text without a role
sphinx became stricter when handling interpreted text without a role,
e.g. "`foo`" since [1], see [2]. This results in errors such as:

  sphinx.errors.SphinxError: cannot determine default role!

In the past, heuristics were used to determine how
to format the text (inline code, italic, ..).

In labgrid, interpreted text without a role is used inconsistently. Most
times it was actually meant to be either inline code ("``foo``"), italic
text or links to docs sections or class definitions.
Fix all such occurrences with explicit variants that actually make sense
in their respective contexts.

[1] https://github.com/sphinx-doc/sphinx/commit/114093cff01562a6a50f8c88b59c7b2fed52a39a
[2] https://github.com/sphinx-doc/sphinx/issues/13904

Signed-off-by: Bastian Krause <bst@pengutronix.de>