remote/exporter: fix stop call in USBSerialPortExport
It fixes:
  TypeError: _stop() missing 1 required positional argument: 'start_params'

This call was missed when stop() was introduced additionally to _stop()
and _stop()'s signature was modified. Calling the public stop method is
what's desired here.

Signed-off-by: Bastian Krause <bst@pengutronix.de>
Fixes: 7585a22 ("remote/exporter: detect when the device path changes and restart ser2net")