github/workflows: always use latest stable docker compose release
docker compose v2.36.2 introduced a regression [1] making labgrid's
docker image generation fail:

  Container staging-dut-1  Creating
  Container staging-coordinator-1  Creating
  Container staging-dut-1  Error response from daemon: No such image: staging-dut:latest
  Error response from daemon: No such image: staging-dut:latest
  Error: Process completed with exit code 1.

The issue has been resolved for nearly a month, but there is still no
GitHub runner image [2] that includes it. It is recommended [3] to use
docker's official setup-compose-action to benefit from stable releases
as early as possible [4]:

  If Docker Compose is already installed on the runner, the action will
  skip download. Otherwise, it will download and install the latest
  stable version available on GitHub.

[1] https://github.com/docker/compose/pull/12896
[2] https://github.com/actions/runner-images/releases
[3] https://github.com/docker/compose/issues/12892#issuecomment-2985440618
[4] https://github.com/docker/setup-compose-action

Signed-off-by: Bastian Krause <bst@pengutronix.de>
(cherry picked from commit 84c494b150ceede8634585aa04d3f04b0bf6d144)