driver/networkusbstoragedriver: fix concatinating tuple to list
The dd command was moved to its own variable during linting, but
accidentally to a tuple and not a list. This leads to an error while
concatinating with self.storage.command_prefix:

  TypeError: can only concatenate list (not "tuple") to list

Fix that.

Fixes: 533cec4c ("linting: do miscellaneous linting")
Signed-off-by: Bastian Stender <bst@pengutronix.de>