ubootdriver: allow handling of console output decoding errors
Some buggy vendor bootloaders can output non ASCII characters to the
serial console:

 00001e50  74 68 20 6e 61 6d 65 20  5b 58 38 36 5f 36 34 20  |th name [X86_64 |
 00001e60  4c 45 44 45 20 4c 69 6e  75 78 2d 73 73 68 5f 5f  |LEDE Linux-ssh__|
 00001e70  5f 67 69 74 5f 64 65 73  69 1f 8b 08 5d 0d 0d 0a  |_git_desi...]...|
                                       |
                                       `-- printf buffer overflow starts here

Which leads to the following decoding issue as the default error handler
is set to `strict`:

    '', before.decode('utf-8'), count=1000000
 UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 6453: invalid start byte

So fix it by allowing overriding of console output decoding errors via
new `console_decodeerrors` config option, so one could use for example
`backslashreplace` decoding error handler.

Signed-off-by: Petr Štetiar <ynezz@true.cz>