factory: recognize invalid config yaml item in _convert_to_named_list()
Caused by copying/pasting the config yaml contains this:

  targets:
    main:
      drivers:
        - SerialDriver:
	- ShellDriver: {}
        ..

This leads to:

  TypeError: 'NoneType' object is not iterable

To help debugging the config error from above now ends with:

  labgrid.exceptions.InvalidConfigError: invalid list item, add empty dict for no arguments

Signed-off-by: Bastian Stender <bst@pengutronix.de>