multiple: remove step kwarg from _run()/run()
_run() methods are not called with step and step is not used anyway, so
remove it.

This fixes errors like:

  TypeError: _run() missing 1 required keyword-only argument: 'step'

Issue introduced by PR #237.

Signed-off-by: Bastian Stender <bst@pengutronix.de>