driver: add missing LXAUSBMuxDriver in __init__.py
This leads to

  labgrid.exceptions.InvalidConfigError: unknown driver class LXAUSBMuxDriver

when used with an environment config.

Fixes: 5a0dcb83 ("add support for Linux Automation USB-Mux")
Signed-off-by: Bastian Krause <bst@pengutronix.de>