labgrid-client: fastboot: use AndroidFastbootDriver.run() for 'oem exec'
Currently, the fastboot command on the exporter will try to parse
parameters from the command which we want to run on the target:

    $ labgrid-client fastboot oem exec state -s
    fastboot: option requires an argument -- 's'
    [.. traceback ..]
    subprocess.CalledProcessError: Command '['ssh', '-x', '-o',
    'ConnectTimeout=5', '-o', 'PasswordAuthentication=no',
    'labgrid-exporter-hostname', '--', 'fastboot', '-i', '0x1337', '-s',
    'usb:2-2.3.2', 'oem', 'exec', 'state', '-s']' returned non-zero exit
    status 1.

AndroidFastbootDriver.run() already adds a '--' after the 'fastboot oem
exec' part, so use that method for 'labgrid-client fastboot' to fix this
behaviour.

Signed-off-by: Roland Hieber <rhi@pengutronix.de>