tests/util: unregister cleanup for explicit cleanup call
Calling SSHConnection's cleanup() method twice (once explicitly in the
test, once on termination via atexit) makes the second shutil.rmtree()
raise an exception as the given path does not exist at this point:

  Error in atexit._run_exitfuncs:
  Traceback (most recent call last):
  An exception occured during cleanup, call the cleanup() method on targets yourself to handle exceptions explictly.
    File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/shutil.py", line 475, in rmtree
      orig_st = os.lstat(path)
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/labgrid-connection-vx8arq97'

Fix that by unregistering the cleanup function for this test.

Fixes: 47682228 ("test: add test for SSHConnection cleanup()")
Signed-off-by: Bastian Krause <bst@pengutronix.de>