tests/stepreporter: mock line() method in MockTW
This fixes the warning:

  labgrid/step.py:44: UserWarning: unhandled exception during event notification: 'MockTW' object has no attribute 'line'
    warnings.warn("unhandled exception during event notification: {}".format(e))

Fixes: c1ed5e0a ("ColoredStepReporter: be compatible with 8-color terminals")
Signed-off-by: Bastian Krause <bst@pengutronix.de>