tests/conftest: fix concurrent access to pexpect.spawn
pexpect/ptyprocess are not thread-safe. But we need a thread to keep
reading the Exporter/Coordinator outputs during the tests for debugging
purposes.

The reader thread (calling
`pexpect.spawn.read_nonblocking()`) and the main thread (calling
`pexpect.spawn`'s `kill()`/`wait()`/`isalive()`) can access it
concurrently. Internally, pexpect calls waitpid(2) in these methods.

This behavior leads to errors such as:

  ptyprocess.util.PtyProcessError: isalive() encountered condition where "terminated" is 0, but there was no child process. Did someone else call waitpid() on our process?

Or:

  pexpect.exceptions.ExceptionPexpect: isalive() encountered condition where "terminated" is 0, but there was no child process. Did someone else call waitpid() on our process?

Fix this by serializing access to pexpect.spawn through a lock.

Signed-off-by: Bastian Krause <bst@pengutronix.de>
(cherry picked from commit 66be067d2bf59394046724481aa60de677202d24)
Signed-off-by: Rouven Czerwinski <rouven.czerwinski@linaro.org>