resource/common: add generic poll function
Since e8efb22 ("target: poll resources directly") resources are polled
instead of their managers. However prior to this change not all
resources implemented a poll function, resulting in the following
errors:
Traceback (most recent call last):
  File "[...]/tests/conftest.py", line 51, in do_barebox_boot
    strategy.transition("barebox")
  File "/usr/ptx-venvs/labgrid/lib/python3.7/site-packages/labgrid/step.py", line 219, in wrapper
    _result = func(*_args, **_kwargs)
  File "/usr/ptx-venvs/labgrid/lib/python3.7/site-packages/labgrid/strategy/graphstrategy.py", line 149, in transition
    self.states[state_name]['method']()
  File "/usr/ptx-venvs/labgrid/lib/python3.7/site-packages/labgrid/step.py", line 219, in wrapper
    _result = func(*_args, **_kwargs)
  File "[...]/my_strategy.py", line 92, in state_barebox
    self.target.activate(self.console)
  File "/usr/ptx-venvs/labgrid/lib/python3.7/site-packages/labgrid/target.py", line 406, in activate
    self.await_resources(resources)
  File "/usr/ptx-venvs/labgrid/lib/python3.7/site-packages/labgrid/target.py", line 83, in await_resources
    r.poll()
AttributeError: 'NetworkSerialPort' object has no attribute 'poll'

In these cases the resource needs to retrieve its own manager and then
poll the manager for changes. Implement the poll function for all
resources in this way.

Signed-off-by: Rouven Czerwinski <r.czerwinski@pengutronix.de>