crossbar-requirements: add six dependency for txtorcon
crossbar 21.3.1 depends on txtorcon. txtorcon's latest release v23.11.0
contains an implicit dependency on six. On its main branch, six is not
used anymore [1].
txtorcon again depends on automat. Prior to automat's latest release
v24.8.0 it depended explicitly on six. With v24.8.0, that's not
the case anymore [2]. That now means six is not installed, thus txtorcon
fails:

  Traceback (most recent call last):
    File "crossbar-venv/bin/crossbar", line 8, in <module>
      sys.exit(run())
               ^^^^^
    File "crossbar-venv/lib/python3.11/site-packages/crossbar/__init__.py", line 175, in run
      _personalities = personalities()
                       ^^^^^^^^^^^^^^^
    File "crossbar-venv/lib/python3.11/site-packages/crossbar/__init__.py", line 213, in personalities
      from crossbar import personality as standalone
    File "crossbar-venv/lib/python3.11/site-packages/crossbar/personality.py", line 39, in <module>
      from crossbar.node import node
    File "crossbar-venv/lib/python3.11/site-packages/crossbar/node/node.py", line 45, in <module>
      from crossbar.router.session import RouterSessionFactory
    File "crossbar-venv/lib/python3.11/site-packages/crossbar/router/session.py", line 49, in <module>
      from crossbar.common.twisted.endpoint import extract_peer_certificate
    File "crossbar-venv/lib/python3.11/site-packages/crossbar/common/twisted/endpoint.py", line 52, in <module>
      import txtorcon
    File "crossbar-venv/lib/python3.11/site-packages/txtorcon/__init__.py", line 11, in <module>
      from txtorcon.router import Router
    File "crossbar-venv/lib/python3.11/site-packages/txtorcon/router.py", line 10, in <module>
      from .util import NetLocation
    File "crossbar-venv/lib/python3.11/site-packages/txtorcon/util.py", line 15, in <module>
      import six
  ModuleNotFoundError: No module named 'six'

To fix this, add the six dependency to our crossbar-requirements.txt.

[1] https://github.com/meejah/txtorcon/issues/395
[2] https://github.com/glyph/automat/pull/149

Signed-off-by: Bastian Krause <bst@pengutronix.de>