doc/getting_started: fix missing python3-setuptools package
setuptools package is needed by pyserial:

 $ pip3 install -r requirements.txt
 $ python3 setup.py install
 ...
 Collecting pyserial from https://github.com/labgrid-project/pyserial/archive/v3.4.0.1.zip#egg=pyserial (from -r requirements.txt (line 4))
   Downloading https://github.com/labgrid-project/pyserial/archive/v3.4.0.1.zip
     Complete output from command python setup.py egg_info:
     Traceback (most recent call last):
       File "<string>", line 1, in <module>
     ModuleNotFoundError: No module named 'setuptools'

I've discovered this while crafting custom Docker image based on
`debian:buster-slim`.

Signed-off-by: Petr Štetiar <ynezz@true.cz>