tests: sshdriver: fix ValueError on cleanup
Since d08a35c5, stdout of the ssh keepalive process is logged. The
return value of the communicate method is used to achieve this. This
leads to ValueErrors during testing:

  Traceback (most recent call last):
    File "/home/runner/work/labgrid/labgrid/labgrid/target.py", line 516, in _atexit_cleanup
      self.cleanup()
    File "/home/runner/work/labgrid/labgrid/labgrid/target.py", line 562, in cleanup
      self.deactivate_all_drivers()
    File "/home/runner/work/labgrid/labgrid/labgrid/target.py", line 512, in deactivate_all_drivers
      self.deactivate(drv)
    File "/home/runner/work/labgrid/labgrid/labgrid/target.py", line 505, in deactivate
      client.on_deactivate()
    File "/home/runner/work/labgrid/labgrid/labgrid/driver/sshdriver.py", line 65, in on_deactivate
      self._stop_keepalive()
    File "/home/runner/work/labgrid/labgrid/labgrid/driver/sshdriver.py", line 565, in _stop_keepalive
      stdout, _ = self._keepalive.communicate(timeout=60)
      ^^^^^^^^^
  ValueError: not enough values to unpack (expected 2, got 0)

This happens also during CI testing, but is not fatal, since it happens
during cleanup.

To prevent this, mock the communicate method. This has also been done in
b8f059fb which has been reverted since (d425be47).

Fixes: d08a35c5 ("sshdriver: Log keepalive output")
Signed-off-by: Bastian Krause <bst@pengutronix.de>