doc/man/pytest: fix inline interpreted text without a role
sphinx became stricter when handling interpreted text without a role,
e.g. "`foo`" since [1], see [2]. This results in errors such as:

  sphinx.errors.SphinxError: cannot determine default role!

In the past, heuristics were used to determine how to format the text
(inline code, italic, ..).

Fix another occurrence that should have been marked as inline code
instead.

[1] https://github.com/sphinx-doc/sphinx/commit/114093cff01562a6a50f8c88b59c7b2fed52a39a
[2] https://github.com/sphinx-doc/sphinx/issues/13904

Signed-off-by: Bastian Krause <bst@pengutronix.de>