github/push-pr-unit-tests: run release workflow only on parent repository
The workflow runs also for pushes to forks, but fails there:

  Error: OIDC exchange failure:
  OIDC token retrieval failed: GitHub: missing or insufficient OIDC token permissions, the ACTIONS_ID_TOKEN_REQUEST_TOKEN environment variable was unset

So prevent the workflow from running on forks.

Signed-off-by: Bastian Krause <bst@pengutronix.de>