doc: IMXUSBDriver/MXSUSBDriver expects images key instead of image path
Specifying an image path directly leads to:

  KeyError: "no path configured for image '/path/to/bootloader.img'"

Clarify that in the documentation.

Signed-off-by: Bastian Stender <bst@pengutronix.de>