pytestplugin/hooks: catch getoption ValueError
In case the logging plugin is not loaded, the option "log_cli_level" is
never registered and getoption fails. Catch the exception and return
from the function since there is nothing for us to configure in this
case. Fixes the following traceback:

  Traceback (most recent call last):
    File "/home/phoenix/work/ptx/labgrid/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1542, in getoption
      val = getattr(self.option, name)
  AttributeError: 'Namespace' object has no attribute 'log_cli_level'

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "/home/phoenix/work/ptx/labgrid/venv/bin/pytest", line 8, in <module>
      sys.exit(console_main())
    File "/home/phoenix/work/ptx/labgrid/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 190, in console_main
      code = main()
    File "/home/phoenix/work/ptx/labgrid/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 167, in main
      ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
    File "/home/phoenix/work/ptx/labgrid/venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
      return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
    File "/home/phoenix/work/ptx/labgrid/venv/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
      return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
    File "/home/phoenix/work/ptx/labgrid/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
      return outcome.get_result()
    File "/home/phoenix/work/ptx/labgrid/venv/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
      raise ex[1].with_traceback(ex[2])
    File "/home/phoenix/work/ptx/labgrid/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
      res = hook_impl.function(*args)
    File "/home/phoenix/work/ptx/labgrid/labgrid/pytestplugin/hooks.py", line 32, in pytest_cmdline_main
      set_cli_log_level(logging.DEBUG)
    File "/home/phoenix/work/ptx/labgrid/labgrid/pytestplugin/hooks.py", line 16, in set_cli_log_level
      current_level = config.getoption("log_cli_level") or config.getini("log_cli_level")
    File "/home/phoenix/work/ptx/labgrid/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1553, in getoption
      raise ValueError(f"no option named {name!r}") from e
  ValueError: no option named 'log_cli_level'

Signed-off-by: Rouven Czerwinski <r.czerwinski@pengutronix.de>